platform :ios, '7.0'

target 'FBSnapshotTestCaseDemoTests', :exclusive => true do
  pod 'FBSnapshotTestCase', :git => 'https://github.com/dblock/ios-snapshot-test-case', :branch => 'fb-snapshot-test-recorder'
  pod 'Specta', '~> 0.2.1'
  
  pod 'EXPMatchers+FBSnapshotTest', :path => "../"
end
