source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'FBSnapshotTestCaseDemoTests' do
  pod 'Specta'
  pod 'Expecta+Snapshots', :path => "../"
end

# Cocoapods bug with static linking and iOSSnapshotTestCase
# https://github.com/CocoaPods/CocoaPods/issues/8231
post_install do |installer|
    def merge_and_link_dirs(source, destination)
        if File.symlink?(source) then
            return
        end

        if File.directory?(source) then
          system "mv #{source}/* #{destination}"
          Dir.rmdir(source)
        end

        File.symlink(destination, source)
    end

    headers_dir = installer.config.project_pods_root + 'Headers/'
    # Work around for FBSnapshotTestCase with static linking.
    # This is needed because of buggy handling of the differing module and project names.
    Dir.chdir(headers_dir + "Public/") do
      merge_and_link_dirs('FBSnapshotTestCase', 'iOSSnapshotTestCase')
    end

    # Cocoapods stomps all over changes to the Private headers in its post-integrate step
    # Remove this and move to the post-integrate hook when cocoapods 1.10 is available.
    system "mv #{headers_dir}/Private/iOSSnapshotTestCase/* #{headers_dir}/Public/iOSSnapshotTestCase"
    # Dir.chdir(headers_dir + "Private/") do
    #     puts "Merge Private"
    #     merge_and_link_dirs('FBSnapshotTestCase', 'iOSSnapshotTestCase')
    # end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = 4.0
      end
    end

  end
